from datetime import datetime
from enum import Enum
from typing import Optional, Iterator


class Replica:
    def __init__(self, path: str, create_if_missing: bool): ...
    @staticmethod
    def new_on_disk(path: str, create_if_missing: bool): ...
    @staticmethod
    def new_in_memory(): ...
    def create_task(self, uuid: str) -> tuple["Task", list["Operation"]]: ...
    def all_task_uuids(self) -> list[str]: ...
    def all_tasks(self) -> dict[str, "Task"]: ...

    def update_task(
        self, uuid: str, property: str, value: Optional[str]
    ) -> dict[str, str]: ...
    def working_set(self) -> "WorkingSet": ...
    def dependency_map(self, force: bool) -> "DependencyMap": ...
    def get_task(self, uuid: str) -> Optional["Task"]: ...
    def import_task_with_uuid(self, uuid: str) -> "Task": ...
    def sync_to_aws(
        self,
        region: str,
        bucket: str,
        access_key_id: str,
        secret_access_key: str,
        avoid_snapshots: bool = False,
    ): ...
    def sync(self): ...
    def rebuild_working_set(self, renumber: bool): ...
    def add_undo_point(self, force: bool) -> None: ...
    def num_local_operations(self) -> int: ...
    def num_undo_points(self) -> int: ...
    def commit_operations(self, operations: list["Operation"]) -> None: ...


class Operation:
    @staticmethod
    def Create(uuid: str) -> "Operation": ...
    @staticmethod
    def Delete(uuid: str, old_task: dict[str, str]): ...

    @staticmethod
    def Update(
        uuid: str,
        property: str,
        timestamp: str,
        old_value: Optional[str],
        value: Optional[str],
    ) -> "Operation": ...
    @staticmethod
    def UndoPoint() -> "Operation": ...


class Status(Enum):
    Pending = 1
    Completed = 2
    Deleted = 3
    Recurring = 4
    Unknown = 5


class Task:
    def get_uuid(self) -> str: ...
    def get_status(self) -> "Status": ...
    def get_taskmap(self) -> dict[str, str]: ...
    def get_entry(self) -> Optional[datetime]: ...
    def get_priority(self) -> str: ...
    def get_wait(self) -> Optional[datetime]: ...
    def is_waiting(self) -> bool: ...
    def is_active(self) -> bool: ...
    def is_blocked(self) -> bool: ...
    def is_blocking(self) -> bool: ...
    def has_tag(self, tag: "Tag") -> bool: ...
    def get_tags(self) -> list["Tag"]: ...
    def get_annotations(self) -> list["Annotation"]: ...
    def get_uda(self, namespace: str, key: str) -> Optional[str]: ...
    def get_udas(self) -> list[tuple[tuple[str, str], str]]: ...
    def get_modified(self) -> Optional[datetime]: ...
    def get_due(self) -> Optional[datetime]: ...
    def get_dependencies(self) -> list[str]: ...
    def get_value(self, property: str) -> Optional[str]: ...
    def set_status(self, status: "Status") -> list["Operation"]: ...
    def set_description(self, description: str) -> list["Operation"]: ...
    def set_priority(self, priority: str) -> list["Operation"]: ...
    def set_entry(self, entry: Optional[str]) -> list["Operation"]: ...
    def set_wait(self, wait: Optional[str]) -> list["Operation"]: ...
    def set_modified(self, modified: Optional[str]) -> list["Operation"]: ...

    def set_value(
        self, property: str, value: Optional[str]
    ) -> Optional["Operation"]: ...
    def start(self) -> list["Operation"]: ...
    def stop(self) -> list["Operation"]: ...
    def done(self) -> list["Operation"]: ...
    def add_tag(self, tag: "Tag") -> list["Operation"]: ...
    def remove_tag(self, tag: "Tag") -> list["Operation"]: ...

    def add_annotation(
        self, annotation: "Annotation") -> list["Operation"]: ...
    def remove_annotation(
        self, annotation: "Annotation") -> list["Operation"]: ...

    def set_due(self, due: Optional[datetime]) -> list["Operation"]: ...
    def set_uda(self, namespace: str, key: str,
                value: str) -> list["Operation"]: ...

    def remove_uda(self, namespace: str, key: str) -> list["Operation"]: ...
    def set_legacy_uda(self, key: str, value: str) -> list["Operation"]: ...
    def remove_legacy_uda(self, key: str) -> list["Operation"]: ...
    def add_dependency(self, uuid: str) -> list["Operation"]: ...
    def remove_dependency(self, uuid: str) -> list["Operation"]: ...


class WorkingSet:
    def __len__(self) -> int: ...
    def largest_index(self) -> int: ...
    def is_empty(self) -> bool: ...
    def by_index(self, index: int) -> Optional[str]: ...
    def by_uuid(self, uuid: str) -> Optional[int]: ...
    def __iter__(self) -> Iterator[tuple[int, str]]: ...
    def __next__(self) -> tuple[int, str]: ...


class Annotation:
    entry: str
    description: str

    def __init__(self) -> None: ...


class DependencyMap:
    def dependencies(self, dep_of: str) -> list[str]: ...
    def dependents(self, dep_on: str) -> list[str]: ...


class Tag:
    def __init__(self, tag: str): ...
    def is_synthetic(self) -> bool: ...
    def is_user(self) -> bool: ...
